"""Curated icon keys a tag may carry (lucide names, kebab-case).

The dashboard maps these to glyphs. ``TagIcon`` is the wire type, so the
allowed set lands in openapi.json as an enum and any drift between the
two repos shows up as a schema diff rather than a runtime 422.
"""

from __future__ import annotations

from enum import Enum

TAG_ICONS: frozenset[str] = frozenset(
    {
        "rocket",
        "megaphone",
        "flag",
        "star",
        "heart",
        "bookmark",
        "tag",
        "hash",
        "zap",
        "flame",
        "sparkles",
        "trophy",
        "target",
        "crown",
        "gem",
        "gift",
        "calendar",
        "clock",
        "timer",
        "hourglass",
        "briefcase",
        "building",
        "store",
        "shopping-cart",
        "credit-card",
        "wallet",
        "banknote",
        "receipt",
        "mail",
        "send",
        "bell",
        "message-square",
        "phone",
        "video",
        "camera",
        "image",
        "music",
        "mic",
        "book",
        "newspaper",
        "file-text",
        "folder",
        "pen-line",
        "code",
        "terminal",
        "bug",
        "wrench",
        "settings",
        "flask-conical",
        "beaker",
        "lightbulb",
        "graduation-cap",
        "globe",
        "map-pin",
        "compass",
        "plane",
        "car",
        "home",
        "users",
        "user",
        "handshake",
        "shield",
        "lock",
        "key",
        "link",
        "share-2",
        "trending-up",
        "bar-chart-3",
        "pie-chart",
        "layers",
        "package",
        "box",
        "puzzle",
        "gamepad-2",
        "coffee",
        "pizza",
        "leaf",
        "sun",
        "moon",
        "cloud",
        "umbrella",
        "smile",
        "ghost",
        "cat",
        "dog",
        "bird",
        "fish",
    }
)

DEFAULT_TAG_ICON = "tag"

TagIcon = Enum(  # type: ignore[misc]
    "TagIcon",
    {key.upper().replace("-", "_"): key for key in sorted(TAG_ICONS)},
    type=str,
)
