"""Unit tests for the feed integrations (fishfish client + sync task)."""

from __future__ import annotations

from types import SimpleNamespace
from unittest.mock import AsyncMock

import pytest

from services.safety.feeds import (
    FISHFISH_SYNC_TASK,
    FishFishClient,
    fishfish_sync_task,
)


def _http(payload, status=200) -> AsyncMock:
    http = AsyncMock()
    response = SimpleNamespace(
        status_code=status,
        json=lambda: payload,
        raise_for_status=lambda: None,
    )
    http.get = AsyncMock(return_value=response)
    return http


class TestFishFishClient:
    @pytest.mark.asyncio
    async def test_fetch_returns_string_domains(self):
        http = _http(["evil.com", "scam.net", 42, None])
        client = FishFishClient(http, api_url="https://api.fishfish.gg/v1/domains")
        assert await client.fetch_domains() == ["evil.com", "scam.net"]

    @pytest.mark.asyncio
    async def test_non_list_response_raises(self):
        http = _http({"error": "nope"})
        client = FishFishClient(http, api_url="https://api.fishfish.gg/v1/domains")
        with pytest.raises(ValueError, match="expected list"):
            await client.fetch_domains()


class TestFishFishSyncTask:
    def test_task_shape(self):
        task = fishfish_sync_task(AsyncMock(), AsyncMock())
        assert task.name == FISHFISH_SYNC_TASK
        assert task.schedule == "0 * * * *"

    @pytest.mark.asyncio
    async def test_sync_swaps_and_reports_counts(self):
        client = AsyncMock()
        client.fetch_domains = AsyncMock(return_value=[f"d{i}.com" for i in range(500)])
        repo = AsyncMock()
        repo.replace_feed = AsyncMock(return_value=(500, 12, {"d0.com"}))

        detail = await fishfish_sync_task(client, repo).fn()

        repo.replace_feed.assert_awaited_once()
        assert detail == {"domains": 500, "purged": 12, "new": 1, "swept_hosts": 0}

    @pytest.mark.asyncio
    async def test_tiny_download_keeps_previous_set(self):
        """A near-empty feed response is a bad download, not a mass
        delisting — the previous set must survive."""
        client = AsyncMock()
        client.fetch_domains = AsyncMock(return_value=["only.com"])
        repo = AsyncMock()

        detail = await fishfish_sync_task(client, repo).fn()

        repo.replace_feed.assert_not_awaited()
        assert detail["skipped"] == "below_sanity_floor"

    @pytest.mark.asyncio
    async def test_fetch_failure_propagates_to_task_result(self):
        """The scheduler records handler exceptions as status=error — the
        client's raise must reach it, not be swallowed here."""
        client = AsyncMock()
        client.fetch_domains = AsyncMock(side_effect=RuntimeError("feed down"))
        repo = AsyncMock()

        with pytest.raises(RuntimeError, match="feed down"):
            await fishfish_sync_task(client, repo).fn()
        repo.replace_feed.assert_not_awaited()


class TestFeedSeeds:
    @pytest.mark.asyncio
    async def test_seeds_only_feeds_that_declare_one_and_are_empty(self):
        from services.safety.feeds import ensure_feed_seeds

        repo = AsyncMock()
        repo.count = AsyncMock(return_value=0)
        repo.replace_feed = AsyncMock(return_value=(31, 0, set()))

        await ensure_feed_seeds(repo)

        # Only the shorteners feed declares a seed today.
        repo.replace_feed.assert_awaited_once()
        assert repo.replace_feed.await_args.args[0] == "shorteners"

    @pytest.mark.asyncio
    async def test_never_reseeds_a_curated_feed(self):
        """Operator removals must survive restarts — a non-empty feed is
        owned by the DB, not by the seed file."""
        from services.safety.feeds import ensure_feed_seeds

        repo = AsyncMock()
        repo.count = AsyncMock(return_value=12)

        await ensure_feed_seeds(repo)

        repo.replace_feed.assert_not_awaited()

    def test_seed_refuses_chosen_shorteners_but_not_platform_wrappers(self):
        """The test is whether the user CHOSE the shortener. Deliberately
        shortening a bit.ly or is.gd link is the laundering shape and gets
        refused; t.co, lnkd.in and buff.ly are generated by the platform on
        share, so refusing them would reject normal tweet and LinkedIn
        links."""
        from services.safety.feeds import load_shortener_seed

        seed = set(load_shortener_seed())
        # general-purpose shorteners: refused
        assert {"bit.ly", "tinyurl.com", "goo.gl", "is.gd", "v.gd"} <= seed
        # cloak redirectors from live campaigns: refused
        assert {"l24.im", "e.vg", "bitly.cx", "vlk.by", "goo.su"} <= seed
        # platform share wrappers: NOT refused
        assert not ({"t.co", "lnkd.in", "buff.ly"} & seed)
        # Serving domains only, never corporate sites, and no stray comments.
        assert "bitly.com" not in seed
        assert not any(d.startswith("#") or " " in d for d in seed)


class TestFeedRegistry:
    """The registry drives composition — these pins are what makes 'add a
    feed = one entry' true."""

    def _settings(self, **overrides):
        from config import SafetySettings

        return SafetySettings(**overrides)

    def test_operator_feeds_are_always_on_fishfish_gates_on_master(self):
        from services.safety.feeds import build_feed_providers

        repo = AsyncMock()
        gate, analyzer, _messages = build_feed_providers(
            self._settings(enabled=False), repo
        )
        assert [p.name for p in gate] == ["feed_manual", "feed_shorteners"]
        assert [p.name for p in analyzer] == ["feed_manual"]

        gate, analyzer, _ = build_feed_providers(self._settings(enabled=True), repo)
        assert "feed_fishfish" in [p.name for p in gate]
        assert "feed_fishfish" in [p.name for p in analyzer]

    def test_shorteners_never_join_the_analyzer(self):
        from services.safety.feeds import build_feed_providers

        _, analyzer, _ = build_feed_providers(self._settings(enabled=True), AsyncMock())
        assert "feed_shorteners" not in [p.name for p in analyzer]

    def test_public_message_comes_from_the_registry(self):
        from services.safety.feeds import build_feed_providers

        _, _, messages = build_feed_providers(self._settings(), AsyncMock())
        assert messages == {
            "feed_shorteners": "Links to other URL shorteners are not allowed"
        }

    def test_sync_tasks_come_from_the_registry(self):
        from services.safety.feeds import FISHFISH_SYNC_TASK, build_feed_tasks

        tasks = build_feed_tasks(self._settings(enabled=True), AsyncMock(), AsyncMock())
        assert [t.name for t in tasks] == [FISHFISH_SYNC_TASK]
        assert (
            build_feed_tasks(self._settings(enabled=False), AsyncMock(), AsyncMock())
            == []
        )
